# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc37d3b5b0bdd06ac8ca2c37053c5346815f59408ccd160c115d2bdd5e4cae927f900dc6c10f52e9b2228c82105cccdd31216b990006f5ba0e7d3429d1c375de

test:
  secret_key_base: d8dd2e678f9e225ccc37e735714d5a6887aaadca03d1d5c684638b77b2a39cb3d118ce2b0a54343c4030667a8ac46c0bf1c965740df41d2eeed34630360921df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
